### PR TITLE
Initialized Variables & added Listener method signatures

### PR DESCRIPTION
**Pull request by WonKan**
Declared and initialized variables for widgets.  Added skeleton Listener methods.

### CODE REVIEW

**Comment by fufufanatic** [comment]
Decent job.

**Comment by WonKan** [comment]
Thanks bro!  I just pulled the copy that you merged.  I see that the third
spinner that you told me about wasn't added.  I wasn't sure if you were
going to add it.  I can add it if you can't.

**Comment by WonKan** [comment]
I just added the new spinner and moved the entry field.

**Comment by fufufanatic** [comment]
Damn, I'm actually adding it right now.

**Pull request merged**
